apiVersion: v1
kind: ConfigMap
metadata:
  name: postgmon-config
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
