apiVersion: v1
kind: Secret
metadata:
  name: postgres-idle-monitor-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
