apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_URL: {{ .Values.postgres.url | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  POSTGRES_USERNAME: {{ .Values.postgres.usename | b64enc | quote }}
